routes/web.php
<?php
Route::get('/', 'Guest\HomeController')->name('home');
Route::post('google-2fa/verify', 'User\Google2faController@verify')->name('profile.google-2fa.verify');

Route::any('wallets/deposit/paypal/response/return-url', 'User\Trader\WalletController@completePayment')->name('frontend.wallets.deposit.paypal.return-url');
Route::any('wallets/deposit/paypal/response/cancel-url', 'User\Trader\WalletController@cancelPayment')->name('frontend.wallets.deposit.paypal.cancel-url');

Route::group(['namespace' => 'TradingView'], function () {
    Route::get('faq', 'FaqController@index')->name('faq.index');
    Route::get('faq/{id}', 'FaqController@show')->name('faq.show');
    Route::get('trading-views', 'TradingViewController@index')->name('trading-views.index');
    Route::get('trading-views/{id}', 'TradingViewController@show')->name('trading-views.show');
    Route::post('trading-views/{id}/comment', 'TradingViewController@comment')->name('trading-views.comment');
});

//Test Route
Route::any('test', 'TestController@test')->name('test');

app/Models/User/UserInfo.php
<?php

namespace App\Models\User;

use App\Models\Core\UserRoleManagement;
use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableInterface;

class UserInfo extends Model implements AuditableInterface
{
    use Auditable;

    protected $fillable = ['user_id', 'first_name', 'last_name', 'address', 'phone', 'is_id_verified', 'id_type', 'id_card_front', 'id_card_back'];

    protected $fakeFields = ['user_id','first_name','last_name', 'country_id', 'address', 'phone', 'is_id_verified', 'id_type', 'id_card_front', 'id_card_back'];

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

resources/views/backend/layouts/includes/_breadcrumb.blade.php
<ol class="breadcrumb">
    <li><a href="{{ route('home')}}"><i class="fa fa-home"></i> Home</a></li>
    @foreach(get_breadcrumbs() as $breadcrumb)
        @if($loop->last || !$breadcrumb['display_url'])
            <li class="active">{{ $breadcrumb['name'] }}</li>
        @else
            <li><a href="{{ $breadcrumb['url'] }}">{{ $breadcrumb['name'] }}</a></li>
        @endif
    @endforeach
</ol>

resources/views/backend/layouts/includes/_content_header.blade.php
<section class="content-header">
    <div class="page-title-bar">
        @include('backend.layouts.includes._breadcrumb')
    </div>
</section>


<section class="system-notices">
    <div class="row">
        @foreach(get_system_notices() as $notice)
            <div class="col-lg-12">
                <div class="alert alert-{{ $notice->type }} alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4>{{ $notice->title }}</h4>
                    {{ $notice->description }}
                </div>
            </div>
        @endforeach
    </div>
</section>

resources/views/backend/layouts/includes/_footer.blade.php
<footer class="main-footer">
    Copyright &copy; {{ date("Y",strtotime("-1 year")).'-'.date('Y') }} <a href="{{ url('/') }}">{{ env('APP_NAME','Cryptomania') }}</a>. All rights reserved.
</footer>

<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
@include('errors.flash_message')
<!-- jQuery 3 -->
<script src="{{ asset('js/app.js') }}?t={{ random_string() }}"></script>
<script src="{{ asset('common/vendors/jquery-ui/jquery-ui.min.js') }}"></script>
<script src="{{ asset('common/vendors/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('common/vendors/iCheck/icheck.min.js') }}"></script>
<script src="{{ asset('backend/assets/js/adminlte.min.js') }}"></script>
@yield('extraScript')
<script src="{{ asset('backend/assets/js/custom.js') }}"></script>
@yield('script')
</body>
</html>

resources/views/backend/layouts/includes/_header.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title') | {{ company_name() }}</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('common/images/favicon-32x32.png') }}">
    @yield('before-style')
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <link rel="stylesheet" href="{{ asset('common/vendors/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('common/vendors/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('backend/assets/css/admin_lte.css') }}">
    <link rel="stylesheet" href="{{ asset('backend/assets/css/template_color.css') }}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('common/vendors/iCheck/all.css') }}">

    <!-- for datatable and date picker -->
    <link rel="stylesheet" href="{{ asset('common/vendors/datepicker/datepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('common/vendors/datatable_responsive/datatables/plugins/bootstrap/datatables.bootstrap.css') }}">
    <link rel="stylesheet" href="{{ asset('common/vendors/datatable_responsive/datatables/datatables.min.css') }}">
    <link rel="stylesheet" href="{{ asset('backend/assets/style.css') }}">

    @yield('after-style')
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    @if( env('APP_ENV') != 'local' && admin_settings('display_google_captcha') == ACTIVE_STATUS_ACTIVE )
        {!! NoCaptcha::renderJs() !!}
    @endif

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

resources/views/backend/layouts/includes/_sidebar.blade.php
<aside class="main-sidebar">
    <div class="sidebar-inside">
        <!-- <div class="menu-text show-in-nav-expanded">Back Panel</div> -->
        <div class="logo-panel">
            <div class="image">
                @if(admin_settings('company_logo'))
                    <img src="{{ get_image(admin_settings('company_logo')) }}" class="img-responsive logo-big show-in-nav-expanded">
                @else
                    <a style="color: #fefefe;text-transform: uppercase" href="{{ route('dashboard') }}" class="navbar-brand "><b>{{ env('APP_NAME') }}</b></a>
                @endif

            <!-- <img src="assets/images/logo-small.png" alt="User Image" class="img-responsive logo-small show-in-nav-collapsed"> -->
            </div>
        </div>
        <a href="javascript:" class="sidebar-toggle" data-toggle="push-menu" role="button"></a>
    </div>
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- sidebar menu: : style can be found in sidebar.less -->
        {!! get_nav('back-end') !!}
        {{--<ul class="sidebar-menu" data-widget="tree">
            <li class="active treeview">
                <a href="javascript:;">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
                </a>
                <ul class="treeview-menu">
                    <li class="active"><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                    <li><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
                </ul>
            </li>

        </ul>--}}
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/backend/layouts/includes/_top_header.blade.php
<header class="main-header">
    <!-- Logo -->
    <!-- <a href="index2.html" class="logo"> -->
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <!-- <span class="logo-mini"><b>A</b>LT</span> -->
    <!-- logo for regular state and mobile devices -->
    <!-- <span class="logo-lg"><b>Admin</b>LTE</span> -->
    <!-- </a> -->
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <!-- <a href="javascript:;" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a> -->

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                @php
                    $userNotifications = get_user_specific_notice();
                @endphp
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">{{ $userNotifications['count_unread'] }}</span>
                    </a>
                    @if(!$userNotifications['list']->isEmpty())
                        <ul class="dropdown-menu">
                            <li class="header text-bold">{{ __('You have :count notifications',['count' => $userNotifications['count_unread']]) }}</li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    @foreach($userNotifications['list'] as $notification)
                                    <li>
                                        <a><i class="fa fa-bell text-orange"></i><span style="color: #000000">{{ str_limit($notification->data, 50) }}</span></a>
                                    </li>
                                        @endforeach
                                </ul>
                            </li>
                            <li class="footer"><a class="bg-green-active" style="color: #FFFFFF !important" href="{{ route('notices.index') }}">View all</a></li>
                        </ul>
                    @endif
                </li>
                <li class="user user-menu">
                    <a href="{{ route('profile.index') }}">
                        <img src="{{ get_avatar(Auth::user()->avatar) }}" class="user-image img-circle" alt="User Image">
                        <span class="hidden-xs cm-ml-5">{{ Auth::user()->userInfo->full_name }}</span>
                    </a>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="{{ route('logout') }}"><i class="fa fa-sign-out"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/backend/layouts/includes/_top_navigation_header.blade.php
<header class="main-header">
    <nav class="navbar navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">
                @if(admin_settings('company_logo'))
                    <a href="{{ route('home') }}" class="navbar-brand"><img
                                style="width: 40px;height: 40px; margin-top: -10px"
                                src="{{ get_image(admin_settings('company_logo')) }}"></a>
                @else
                    <a style="text-transform: uppercase" href="{{ route('home') }}" class="navbar-brand"><b>{{ env('APP_NAME') }}</b></a>
                @endif

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse">
                    <i class="fa fa-bars"></i>
                </button>
            </div>

            <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="{{ is_current_route('home') }}"><a href="{{ route('home') }}">{{ __('Home') }}</a></li>
                    <li class="{{ is_current_route('exchange.index') }}"><a
                                href="{{ route('exchange.index') }}">{{ __('Exchange') }}</a></li>
                    <li class="{{ is_current_route('exchange.ico.index') }}"><a
                                href="{{ route('exchange.ico.index') }}">{{ __('ICO') }}</a></li>
                    <li class="{{ is_current_route('trading-views.index') }}"><a
                                href="{{ route('trading-views.index') }}">{{ __('Trading View') }}</a></li>
                    <li class="{{ is_current_route('faq.index') }}"><a
                                href="{{ route('faq.index') }}">{{ __('FAQ') }}</a></li>
                </ul>
            </div>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                @auth
                    <!-- User Account: style can be found in dropdown.less -->
                        @php
                            $userNotifications = get_user_specific_notice();
                        @endphp
                        <li class="dropdown notifications-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-bell-o"></i>
                                <span class="label label-warning">{{ $userNotifications['count_unread'] }}</span>
                            </a>
                            @if(!$userNotifications['list']->isEmpty())
                                <ul class="dropdown-menu">
                                    <li class="header text-bold">{{ __('You have :count notifications',['count' => $userNotifications['count_unread']]) }}</li>
                                    <li>
                                        <!-- inner menu: contains the actual data -->
                                        <ul class="menu">
                                            @foreach($userNotifications['list'] as $notification)
                                                <li>
                                                    <a><i class="fa fa-bell text-orange"></i><span
                                                                style="color: #000000">{{ str_limit($notification->data, 50) }}</span></a>
                                                </li>
                                            @endforeach
                                        </ul>
                                    </li>
                                    <li class="footer"><a class="bg-green-active" style="color: #FFFFFF !important"
                                                          href="{{ route('notices.index') }}">View all</a></li>
                                </ul>
                            @endif
                        </li>
                        <li class="user user-menu">
                            <a href="{{ route('profile.index') }}">
                                <img src="{{ get_avatar(Auth::user()->avatar) }}" class="user-image img-circle"
                                     alt="User Image">
                                <span class="hidden-xs cm-ml-5">{{ Auth::user()->userInfo->full_name }}</span>
                            </a>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                        <li>
                            <a href="{{ route('logout') }}"><i class="fa fa-sign-out"></i></a>
                        </li>
                    @endauth
                    @guest
                        <li>
                            <a href="{{ route('login') }}">{{__('Login')}}</a>
                        </li>

                        <li>
                            <a href="{{ route('register.index') }}">{{ __('Register') }}</a>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>
</header>